### ISSUE TITLE
Options to adjust `can't load` warnings

### ISSUE THREAD

**Issue by imrehg** [resin-io/valletta#7]
Most customizations are unlikely to use all available template file types, have an option to suppress those warnings for clarity, or flip it on its head, and only log the files that are actually included (not highlighting the ones that were not)

**Comment by LucianBuzzo** [comment]
@imrehg I've updated the [MVP PR](https://github.com/resin-io/valletta/pull/3) so that it will only warn you if valletta fails to load a file that you've explicitly added to your config.
